@startuml DS-03_RF04_notificacion
skinparam shadowing false

actor Sistema
participant "Scheduler" as SCH
participant "ServicioNotificacion" as SN
database BD
participant "UI Usuario" as UI
SCH -> SN: revisarVencimientos()
SN -> BD: prestamosProximos()
BD --> SN: lista
SN -> BD: crearAlertaInterna()
UI -> SN: alIniciarSesion()
SN --> UI: mostrarNotificacion

@enduml
